name: test1
on:
    push:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout soure
          uses: actions/checkout@v3
          
        - name: Deploy to Railway
          run: railway up