name: test1
on:
    push:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout soure
          uses: actions/checkout@v3
          
          # name: i want to deploy railway
          # uses: bervProject/railway-deploy@main
          # with:
          #   railway_token: ${{ secrets.RAILWAY_TOKEN }}
          #   service: "yielding-crow"

        - name: Send to my Slack workflow
          id: slack
          uses: slackapi/slack-github-action@v1.23.0
          with:
              payload: | 
                {
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "*DipSA 56 CI/CD Submission*"
                      }
                    },
                    {
                      "type": "divider"
                    },
                    {
                      "type": "section",
                      "fields": [
                        {
                          "type": "mrkdwn",
                          "text": "*Name*:XU YUNLEI"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Email*:e1112888@u.nus.edu"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Metriculation*:E1112888"
                        },
                        {
                          "type": "mrkdwn",
                          "text": "*Repository*:"
                        }
                      ]
                    },
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "Railway_token."
                      },
                      "accessory": {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "Go"
                        },
                        "style": "primary",
                        "action_id": "button_click"
                      },
                      "block_id": "right_button"
                    }
                  ]
                }
          env:
              SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
              SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        
        